### PR TITLE
New layer type "Gated Recurrent Unit" (GRU)

### PR DESCRIPTION
**Pull request by hunyadi**
This pull request introduces support for a new layer type GRU (Gated Recurrent Unit).

### CODE REVIEW

**Comment by Dobiasd** [comment]
Hi Levente,

as discussed via email, I'm very happy about this contribution. :slightly_smiling_face:

Some minor remarks:

1) The test coverage looks OK. Maybe just add one `GRU` with `use_bias=True`. The current ones all have `use_bias=False`.

2) You probably already found the missing cast resulting in the error on travis: https://travis-ci.org/Dobiasd/frugally-deep/builds/460427446#L4620

3) It seems `const std::string& fdeep::model::name() const;` was accidentally deleted while merging.

4) In `json_object_get` I suggest renaming `ValueT&& value` to `ValueT&& default_value`, to make its meaning more explicit.

But really great work overall. I'm looking forward to seeing the tests pass. :+1:

**Comment by hunyadi** [comment]
`use_bias=True` has induced some weird run-time errors that I have not been able to track down. Basically, `bias` is expected to be a matrix of size [2, 3*_n_] where _n_ is the number of GRU units in the layer. However, by the time the data gets to `gru_impl`, it is of the wrong shape, and there are (occasionally) insufficient elements. (Some inputs pass, others fail with this setup.) `weights` and `recurrent_weights` always seem to have the right shape. `create_gru_layer` does trivial transformation, and the code structure reflects the implementation structure of LSTM so I am somewhat at a loss where the error originates from. If you could take a look, it would be super helpful.

**Comment by Dobiasd** [comment]
To debug the bias issue I just ran the code from this PR locally. When changing the `GRU` layers to `use_bias=True`, I also run into the `invalid shape` error in `eigen_row_major_mat_from_values`.

Then while looking at the weight shapes during export, I observed `show_gru_layer` in `convert_model.py` is only called **2** times, despite there being **3** GRU layers in the test model. Can you confirm this observation? And if so, do you know why this is the case?

**Comment by hunyadi** [comment]
As far as I could deduce from the code, the export module (as well as the C++ implementation) treats bidirectional layers specially. Rather than exporting a bidirectional wrapper layer without weights and a true (LSTM or GRU) layer with weights, it saves the weights directly with the bidirectional layer, which are then forwarded to the LSTM or GRU layer C++ implementation when the appropriate class is instantiated. I am being somewhat speculative here as I did not deep dive into the implementation of _bidirectional_layer_, I just implicitly assumed it works as advertised, and try to wire things in the same manner as with LSTM.

Experimenting with various configurations in _get_test_model_recurrent_, it seems `use_bias` only causes an issue when used in conjunction with _Bidirectional_. That said, a quick workaround would be to eliminate the _Bidirectional_ wrapper and then we can have `use_bias` in both ways. But it would be nice to understand the root cause.

**Comment by Dobiasd** [comment]
@n-Guard Maybe you can enlighten us? :)

**Comment by hunyadi** [comment]
I am suspecting a Keras issue here. Below is what I get when I inspect the HDF5 file directly (produced by `generate_test_models.py`):
```
>>> f['model_weights']['gru_1']['gru_1']['bias:0']
<HDF5 dataset "bias:0": shape (2, 12), type "<f4">
>>> f['model_weights']['bidirectional_4']['bidirectional_4']['forward_gru_2']['bias:0']
<HDF5 dataset "bias:0": shape (18,), type "<f4">
```
The first item corresponds to a regular GRU layer with 4 units; the bias matrix has the expected shape of [2,12] where 12 = 3 * _number of units_ = 3 * 4. The second item is a bidirectional GRU layer with 6 units, and the bias matrix appears to have lost a row: it should have a shape of [2,18] where 18 = 3 * 6 but it turns out to be a vector rather than a matrix in HDF5.

That said, I think this is an issue beyond our reach.

**Comment by Dobiasd** [comment]
Good investigation work!

Can you test if Keras is able to load such a model again and do correct predictions with it? In case the answer is yes, it must be possible to work correctly with what is stored. Maybe Keras re-creates the correct bias matrix, and the second row has to be just a bunch of of `1`s?

In case we do not manage to support bias for GRU layers in frugally deep, we should disallow bias on GRU already in `convert_model.py` and let it crash already there, instead of waiting for the C++ part to raise the exception later.

**Comment by Dobiasd** [comment]
Oh, I only now see that you pushed a commit working around this Keras issue. Cool! So is there anything left to do on this PR from your point of view?

**Comment by Dobiasd** [comment]
Just checked the calls to `show_gru_layer`.

Interestingly with the new version of the test model, `show_gru_layer` is called four times, instead of two times.

---

So this:

```python
    gru1 = GRU(units=4, return_sequences=True)(inp)
    gru2 = Bidirectional(GRU(units=6, return_sequences=True))(gru1)
    gru3 = GRU(units=10, return_sequences=False)(gru2)
    outputs.append(gru3)
```

makes ``show_gru_layer` being called 4 times.

---

While that:

```python
    gru1 = Bidirectional(GRU(units=4, return_sequences=True))(inp)
    gru2 = Bidirectional(GRU(units=6, return_sequences=True))(gru1)
    gru3 = GRU(units=10, return_sequences=False)(gru2)
    outputs.append(gru3)
```

makes ``show_gru_layer` being called 2 times.

---

However this seems to have nothing to do with the newly added GRU implementation, because it's also the case on master with the LSTM layers (just checked):

`get_test_model_recurrent` instantiates (and uses) 5 `LSTM` layers, but during conversion `show_lstm_layer` is only called 4 times. I created [a separate issue](https://github.com/Dobiasd/frugally-deep/issues/98) to track this problem, so we might be able to ignore it here in this PR.

**Comment by hunyadi** [comment]
It is quite possible that Keras performs magic behind the scenes, e.g. it might reconstitute the full _GRU_ bias matrix combining the forward and backward bias vectors, I have not done a thorough investigation in this regard. However, I am strongly in favor of merging the pull request (as well as our other pull request related to the Embedding), which would allow us to rebase to the public github version as opposed to relying on our private enterprise version. I would defer patching _Bidirectional_ to a future pull request. (But, needless to say, I leave it up to you to decide.)

Given what I saw how the code works regarding bidirectional layers, I am not surprised about how many times `show_gru_layer` is called. As I wrote above in a previous comment, whenever a layer is wrapped in a _Bidirectional_, what happens internally, as far as I see, is not that a wrapper is created around the wrapped layer, i.e. a _Bidirectional_ around an _LSTM_ or _GRU_ but a new layer type comes into existence, let us call it _BidirectionalLSTM_ or _BidirectionalGRU_. (The loose typing in Python allows both to be called _Bidirectional_.) This new layer type has parameters like _forward_bias_ and _backward_bias_, which substitutes the original parameters the original layer type had. I would suppose `show_bidirectional_layer` is called for each "missing" `show_lstm_layer` or `show_gru_layer`. I assume this total number of calls would be 6 in either case. (I do not know why the `show_*` functions are called twice but this has been so before we contributed anything to the code base, and I feel this is again beyond the scope of the pull request.

**Comment by Dobiasd** [comment]
Of course you are absolutely right. The open questions have nothing to do with this fine PR. :+1:

Also I was able to verify your assumption about the sum of the calls being equal (see [issue](https://github.com/Dobiasd/frugally-deep/issues/98#issuecomment-442826730).

**Comment by Dobiasd** [comment]
The question regarding the duplicate calls to the `show_` functions is solved now (see [issue](https://github.com/Dobiasd/frugally-deep/issues/98#issuecomment-442830618)).

For tracking the problem with invalid shape of bias matrix for GRU inside Bidirectional layer, I opened a [separate issue](https://github.com/Dobiasd/frugally-deep/issues/99).

**Pull request merged**
