### PR TITLE
add relu6 layer support for MobileNet

### PR DESCRIPTION
**Pull request by bobyguo**
ref: https://www.tensorflow.org/api_docs/python/tf/nn/relu6

### CODE REVIEW

**Comment by Dobiasd** [comment]
Good work! Thanks a lot.
Did you test the implementation by adding something to `get_test_model_small` in `keras_export/generate_test_models.py` temporarily or by running MobileNet?

**Comment by Dobiasd** [comment]
Yes, of course. Sorry. :wink: 

However just having `relu6` in frugally-deep is not enough. We need to be able to convert `mobilenet` from `h5` to `json` using `convert_model.py`.
But even trying to only `load_model('mobilenet.h5')` fails:

```
frugally-deep/build $ ../keras_export/convert_model.py mobilenet.h5 mobilenet.json
loading mobilenet.h5
Traceback (most recent call last):
  File "../keras_export/convert_model.py", line 426, in <module>
    main()
  File "../keras_export/convert_model.py", line 422, in main
    convert(in_path, out_path)
  File "../keras_export/convert_model.py", line 369, in convert
    model = load_model(in_path)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/_impl/keras/engine/saving.py", line 240, in load_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/_impl/keras/engine/saving.py", line 317, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/_impl/keras/layers/serialization.py", line 63, in deserialize
    printable_module_name='layer')
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/_impl/keras/utils/generic_utils.py", line 171, in deserialize_keras_object
    list(custom_objects.items())))
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/_impl/keras/engine/network.py", line 1060, in from_config
    process_layer(layer_data)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/_impl/keras/engine/network.py", line 1046, in process_layer
    layer = deserialize_layer(layer_data, custom_objects=custom_objects)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/_impl/keras/layers/serialization.py", line 63, in deserialize
    printable_module_name='layer')
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/_impl/keras/utils/generic_utils.py", line 173, in deserialize_keras_object
    return cls.from_config(config['config'])
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/_impl/keras/engine/base_layer.py", line 473, in from_config
    return cls(**config)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/_impl/keras/layers/core.py", line 305, in __init__
    self.activation = activations.get(activation)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/_impl/keras/activations.py", line 135, in get
    return deserialize(identifier)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/_impl/keras/activations.py", line 126, in deserialize
    printable_module_name='activation function')
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/_impl/keras/utils/generic_utils.py", line 191, in deserialize_keras_object
    function_name)
ValueError: Unknown activation function:relu6
```

So even if `DepthwiseConv2D` would be supported, we would not be able to use mobilenet yet.

**Comment by bobyguo** [comment]
Sorry, I make a mistake. 
I have tested with the change of "convert_model.py"
```
def relu6(x):
    return K.relu(x)
...
model = load_model(in_path, custom_objects={
                   'relu6': relu6})
```
But this is not standard... Do you have some better ideas?

**Comment by Dobiasd** [comment]
I guess you mean
```python
def relu6(x):
    return K.relu(x, max_value=6)
```

But no, I don't have a better idea right now. I this we just have to trust `relu6` to always mean the same thing, so the `fdeep` implementation returns the wanted results.

**Comment by Dobiasd** [comment]
If I understand correctly, `convert_model.py` would always need to do
```python
model = load_model(in_path, custom_objects={'relu6': relu6})
```
even on models that don't use `relu6`, because it can never know in advance, right?

**Comment by bobyguo** [comment]
yes, this is what I mean.

**Comment by Dobiasd** [comment]
Excellent argument!
So yes, if you commit the needed changes to `convert_model.py` we can merge the PR.

**Comment by bobyguo** [comment]
I would ask Keras first, if relu6 can be defined as standard layer. And Keras in Tensorflow current version has no "DepthwiseConv2D" layer. May be we should wait a moment.

**Comment by bobyguo** [comment]
@Dobiasd 
I have asked Keras, if relu6 can be defined as standard function, but it has not been accepted. The reason please see https://github.com/keras-team/keras/pull/9853.

Would you please check my last commit? The custom function 'DepthwiseConv2D' will be removed if Tensorflow merge with Keras 2.1.5.

**Comment by Dobiasd** [comment]
OK, I understand the reasons François is giving.

Regarding your commit: Using `_impl` does not look very stable, but for a temporary workaround it's OK, I guess.  Now we only need a `DepthwiseConv2D` implementation in `fdeep`. :) It should be quite similar to `SeparableConv2D`.

**Comment by Dobiasd** [comment]
@bobyguo Are you interested in trying to implement `DepthwiseConv2D` in `fdeep`? Otherwise I would try to take a look at it during the next few days.

**Comment by bobyguo** [comment]
@Dobiasd 
I have tried, but I don’t think I can do it well. It would be great if you could implement it. I am very glad to test it. Thank you for your great work!

**Comment by Dobiasd** [comment]
OK, I'll do so. However I will already merge this PR (and then add some unit tests), because it is an isolated feature and implemented well.

**Comment by bobyguo** [comment]
@Dobiasd MobileNetV2 works perfectly too!

**Pull request merged**
