### PR TITLE
Add vcpkg install instruction

### LINKED ISSUE #276: FYI: vcpkg port
With https://github.com/microsoft/vcpkg/pull/17559 (as soon as the PR is merged) this library will be available in https://github.com/microsoft/vcpkg . 

Usage instructions: 
`vcpkg install frugally-deep`

and then the normal way with cmake 
```cmake
find_package(frugally-deep CONFIG REQUIRED)
target_link_libraries(main PRIVATE frugally-deep::fdeep)
```

### PR DESCRIPTION
**Pull request by mathisloge**
Additionally I`ve added syntax highlighting to the cmake code snippet in the hunter section. If you don't like that, i remove that.

closes #276

### CODE REVIEW

**Comment by Dobiasd** [comment]
Perfect, thanks a lot!

And yes, I like the syntax highlighting. :slightly_smiling_face:

**Comment by Dobiasd** [comment]
@mathisloge The latest frugally-deep version on vcpkg is `0.15.10-p0`, so it's a few versions behind.

How can I push the newer versions to vcpkg?

**Comment by mathisloge** [comment]
Hi @Dobiasd,

the general workflow is as follows: 

* Fork the vcpkg repo https://github.com/microsoft/vcpkg
* Create a update branch
* Update the version in https://github.com/microsoft/vcpkg/blob/62d01b70df227850b728f5050418b917ad6d2b32/ports/frugally-deep/vcpkg.json#L3
* Update the REF in https://github.com/microsoft/vcpkg/blob/62d01b70df227850b728f5050418b917ad6d2b32/ports/frugally-deep/portfile.cmake#L4
* Update the sha512 in https://github.com/microsoft/vcpkg/blob/62d01b70df227850b728f5050418b917ad6d2b32/ports/frugally-deep/portfile.cmake#L5 => I'm usually just typing `vcpkg install frugally-deep` as vcpkg throws then an error with the expected sha and the new sha. Then I just copy the new sha from the console output. 
* Commit the changes
* Run vcpkg x-add-version --all
* Commit the new changes
* Create a PR and wait for the maintainers to approve it.

That should be it. 👍

**Comment by Dobiasd** [comment]
Thanks a lot for the quick and awesome response. :heart: I guess I'll be able to do this. :+1:

**Comment by Dobiasd** [comment]
But now, in general, I wonder why one needs to do this by hand. Sounds like something that could be automated on vcpkg side, i.e., when a new tag is pushed for a lib, it does that stuff on its own.

Any idea why this is not implemented?

**Comment by mathisloge** [comment]
But I think I will link this issue to get some real world needs.

**Comment by Dobiasd** [comment]
Thanks a lot! Having this automated would be awesome. :rocket:

I can't imagine wanting to do this manual process every time I release a new version. I'd probably prefer to instead remove any mention of vcpkg from the docs of frugally-deep.

**Comment by mathisloge** [comment]
> I can't imagine wanting to do this manual process every time I release a new version. I'd probably prefer to instead remove any mention of vcpkg from the docs of frugally-deep.

I can totally understand this! It is really tedious.

**Pull request merged**
